# railway.yml
services:
  primary: # O nome exato do seu serviço é "Primary"
    build:
      # Tentar usar o buildpack Node.js
      builder: nodejs
      # Se precisar instalar ffmpeg via railpack, pode ser assim, mas ainda pode falhar
      # runtimes:
      #   - railpack:
      #       runtime_packages:
      #         - ffmpeg
    deploy:
      # Comando para iniciar o N8N. VERIFIQUE O COMANDO CORRETO.
      startCommand: npm start # Ou npx @workflow/n8n start, etc.
