name: Build & Push n8n-ffmpeg
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - Dockerfile
      - .github/workflows/docker-publish.yml
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            carlosguimaraes76/n8n-ffmpeg:${{ github.sha }}
            carlosguimaraes76/n8n-ffmpeg:latest
